"""Mira Activate BLE coordinator.

A single persistent BLE connection per config entry. Serializes all app-layer
ops over the queue (spec §3.3 — "no per-frame sequence id, queue is strictly
serialized"). 10s op timeout per Lf5/c;->i.

Routes through HA's bluetooth integration (bleak-esphome backend), so any
configured BT proxy is used transparently.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import timedelta
from time import monotonic
from typing import Any

from bleak import BleakClient
from bleak.backends.device import BLEDevice
from bleak_retry_connector import (
    BleakClientWithServiceCache,
    establish_connection,
)
from homeassistant.components.bluetooth import (
    async_address_present,
    async_ble_device_from_address,
    async_discovered_service_info,
    async_register_callback,
    BluetoothCallbackMatcher,
    BluetoothChange,
    BluetoothScanningMode,
    BluetoothServiceInfoBleak,
)
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator, UpdateFailed

from .mira_protocol import (
    FrameAssembler,
    IncompleteError,
    InvalidFrameError,
    NOTIFY_CHAR_UUID,
    device_id_from_name,
    OP_SET_TEMPERATURE,
    OP_UNIT_PRIME,
    OUTLET_BIT_0,
    OUTLET_BIT_1,
    OUTLET_BIT_2,
    OUTLET_PAUSE,
    SERVICE_UUID,
    WRITE_CHAR_UUID,
    frame_set_temperature,
    frame_unit_prime,
    parse_unit_prime,
)

_LOGGER = logging.getLogger(__name__)

DOMAIN = "mira_activate"
# 30s — Mode integration's setting. The Activate drops the BLE link after
# ~36s idle, so each poll usually triggers a reconnect. The actual
# responsiveness floor is dominated by reconnect time, not poll cadence.
POLL_INTERVAL = timedelta(seconds=10)  # was 30 — trade BT load for faster
                                       # detection of panel-side state changes
OP_TIMEOUT = 10.0  # Activate's notifications sometimes arrive 4-8s after the
                   # write; shorter timeouts just give up before the reply.

# Hold the link without hammering the proxy. The Activate firmware idle-drops
# the BLE link after ~36s of no GATT activity; a lightweight keepalive just
# inside that window keeps the connection up so we avoid the connect/op/drop
# churn that saturates a shared BT proxy. Fires only when no real op has run
# recently, so it adds zero load while the coordinator is actively polling.
KEEPALIVE_INTERVAL = 22.0  # seconds (< ~36s firmware idle-drop)

# When polls keep failing (marginal RF / broken bond), backing off stops the
# 10s reconnect churn from hammering a struggling link and flooding the log.
# Interval doubles per consecutive failure up to this cap, then resets on the
# first good poll.
BACKOFF_MAX = timedelta(seconds=120)


class MiraActivateCoordinator(DataUpdateCoordinator[dict[str, Any]]):
    """One-connection-per-device coordinator."""

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> None:
        super().__init__(
            hass,
            _LOGGER,
            name=f"mira_activate[{entry.data['address']}]",
            update_interval=POLL_INTERVAL,
        )
        self.entry = entry
        self.address: str = entry.data["address"]
        # Stable per-unit id (from the advertised name). The BLE address can be
        # regenerated by the shower, so we use this to re-find it after a rotation
        # and to key the device-registry entry so entities survive the change.
        self._device_id: str | None = entry.data.get("device_id")
        # Stable unique-id base for entities and the device-registry entry.
        # Prefer the name-id so identifiers survive a BLE-address rotation; fall
        # back to the address only for legacy entries that never parsed a name-id.
        self.unique_base: str = self._device_id or self.address
        self.device_info = DeviceInfo(
            identifiers={(DOMAIN, self.unique_base)},
            name=entry.title or f"Mira Activate {self.address}",
            manufacturer="Mira (Kohler)",
            model="Mira Activate",
            connections={("bluetooth", self.address)},
        )
        self._client: BleakClient | None = None
        self._lock = asyncio.Lock()  # serializes ops, per spec §3.3
        self._assembler = FrameAssembler()
        self._response_event: asyncio.Event = asyncio.Event()
        self._last_frame: Any = None
        self._unsub_bt_callback = None
        self._heartbeat_task: asyncio.Task | None = None
        self._last_op: float = 0.0  # monotonic ts of last successful round-trip
        self._fail_count: int = 0   # consecutive poll failures (drives backoff)
        # Cached state pushed to entities (see AB_2B_DECODE.md).
        # outlet1_on / outlet2_on / outlet0_on are booleans driven by the
        # bit-packed outlet_state byte in payload[13]. flow_lpm is what we'll
        # echo back in the next 0xAB write (× 4 over the wire).
        self._state: dict[str, Any] = {
            "available": False,
            "session_ready": False,
            "running": False,
            "outlet0_on": False,
            "outlet1_on": False,
            "outlet2_on": False,
            "target_temp": 38.0,
            "flow_lpm": 12,  # sane default; gets replaced on first poll
            "measured_temp": None,
            "status_code": None,
            "iot_status": None,
            "paused": False,
            "error": False,
            "raw_status0": None,
            "raw_outlet_state": None,
        }

    # ---- Lifecycle ----------------------------------------------------------

    async def async_init(self) -> None:
        """Register for BT availability callbacks. Do not block setup."""
        self._unsub_bt_callback = async_register_callback(
            self.hass,
            self._on_bt_advertisement,
            BluetoothCallbackMatcher(address=self.address),
            BluetoothScanningMode.PASSIVE,
        )
        # Schedule first refresh in the background
        self.hass.async_create_task(self.async_config_entry_first_refresh())
        # Keepalive: hold the link inside the firmware's idle-drop window.
        self._heartbeat_task = self.hass.async_create_background_task(
            self._heartbeat(), name=f"{DOMAIN}_keepalive[{self.address}]"
        )

    async def async_close(self) -> None:
        if self._unsub_bt_callback is not None:
            self._unsub_bt_callback()
            self._unsub_bt_callback = None
        if self._heartbeat_task is not None:
            self._heartbeat_task.cancel()
            self._heartbeat_task = None
        await self._disconnect()

    # ---- BT callbacks -------------------------------------------------------

    @callback
    def _on_bt_advertisement(
        self, service_info: BluetoothServiceInfoBleak, change: BluetoothChange
    ) -> None:
        """Track availability based on advertising presence."""
        was_available = self._state["available"]
        self._state["available"] = True
        if not was_available:
            self.async_set_updated_data(self._state)

    # ---- Connection management ---------------------------------------------

    async def _get_ble_device(self) -> BLEDevice | None:
        dev = async_ble_device_from_address(self.hass, self.address, connectable=True)
        if dev is not None or not self._device_id:
            return dev
        # Stored address is gone — the Activate likely regenerated its random
        # address. Re-resolve the current address by the stable name-id so we
        # follow the rotation without needing a fresh discovery/re-add.
        for info in async_discovered_service_info(self.hass):
            if (
                info.connectable
                and SERVICE_UUID in info.service_uuids
                and device_id_from_name(info.name) == self._device_id
            ):
                if info.address != self.address:
                    _LOGGER.warning(
                        "Activate %s address rotated %s -> %s; following",
                        self._device_id, self.address, info.address,
                    )
                    self.address = info.address
                return async_ble_device_from_address(
                    self.hass, self.address, connectable=True
                )
        return dev

    async def _ensure_connected(self) -> BleakClient:
        if self._client is not None and self._client.is_connected:
            return self._client
        return await self._connect_and_bond(retry_after_clear=True)

    async def _connect_and_bond(self, retry_after_clear: bool) -> BleakClient:
        """Connect and enable notifications. If start_notify fails with
        Insufficient authentication, run a pair() and retry; if still failing,
        clear the proxy's bond cache and recurse once."""
        device = await self._get_ble_device()
        if device is None:
            raise UpdateFailed(f"Device {self.address} not in BT registry")
        _LOGGER.debug(
            "Establishing BLE connection to %s (retry_after_clear=%s)",
            self.address, retry_after_clear,
        )
        client = await establish_connection(
            BleakClientWithServiceCache,
            device,
            self.address,
            disconnected_callback=self._on_disconnected,
            max_attempts=3,
        )
        self._assembler.reset()
        self._response_event.clear()

        # Fast path: try start_notify without an explicit pair() — saves
        # 1-2s on every reconnect when the proxy is still bonded.
        try:
            await client.start_notify(NOTIFY_CHAR_UUID, self._on_notify)
            if await self._verify_link(client):
                self._client = client
                return client
            # start_notify "succeeded" but the link is not actually usable
            # (CCCD subscribe can return OK on a stale/half-broken bond while
            # encrypted GATT ops still fail). Fall through to pair() recovery.
            _LOGGER.warning("CCCD subscribe OK but link verify failed — running pair() recovery")
        except Exception as exc:  # noqa: BLE001
            if "Insufficient authentication" not in str(exc):
                raise
            _LOGGER.warning("CCCD auth fail — running pair() recovery")

        try:
            await client.pair()
            await asyncio.sleep(0.5)
        except Exception as pexc:  # noqa: BLE001
            _LOGGER.warning("pair() during recovery raised: %s", pexc)

        verify_failed = False
        try:
            await client.start_notify(NOTIFY_CHAR_UUID, self._on_notify)
            if await self._verify_link(client):
                self._client = client
                return client
            verify_failed = True
        except Exception as exc2:  # noqa: BLE001
            if "Insufficient authentication" not in str(exc2) or not retry_after_clear:
                raise

        if verify_failed and not retry_after_clear:
            # Recursion already bounded — don't loop again; surface a failure
            # rather than handing back a known-broken session.
            raise UpdateFailed(
                f"BLE link to {self.address} unusable after bond-cache clear"
            )

        _LOGGER.warning("Still auth=5 after re-pair — clearing proxy bond cache")
        await self._clear_cache_via_client(client)
        try:
            await client.disconnect()
        except Exception:  # noqa: BLE001
            pass
        self._client = None
        # The bond may be stale on a *different* proxy than this one — clear it
        # everywhere so the fresh reconnect can re-bond on whichever proxy wins.
        await self._clear_bonds_all_proxies()
        await asyncio.sleep(2.0)
        return await self._connect_and_bond(retry_after_clear=False)

    async def _verify_link(self, client: BleakClient) -> bool:
        """Confirm the BLE link is actually usable after start_notify.

        start_notify (a CCCD subscribe) can return OK on a stale/half-broken
        bond while encrypted GATT ops still fail. We probe with a real op that
        surfaces the auth error: a *write-with-response* of the benign 0x2B
        unit-prime query to WRITE_CHAR_UUID (267f0002). That char has the Write
        property (so a Write Request is accepted) and an awaited write WILL
        surface "Insufficient authentication/authorization" on a broken bond.
        NB: a read of the notify char (267f0003, Notify-only / no Read property)
        or a response=False write would NOT reliably surface it — both look
        "successful" on a dead link, making the verify a no-op.

        Returns True if usable, False on the known auth-fail broken-bond case
        (caller escalates to pair()/cache-clear). Other errors are treated as
        usable (don't escalate on transient noise).
        """
        try:
            await client.write_gatt_char(
                WRITE_CHAR_UUID, frame_unit_prime(), response=True
            )
            return True
        except Exception as exc:  # noqa: BLE001
            msg = str(exc)
            if "Insufficient authentication" in msg or "Insufficient authorization" in msg:
                _LOGGER.warning("link verify probe hit auth fail (broken bond): %s", exc)
                return False
            _LOGGER.debug("link verify probe raised (non-auth, treated as usable): %s", exc)
            return True

    def _proxy_api_client(self, client: BleakClient):
        """Reach the underlying aioesphomeapi APIClient via the bleak-esphome
        backend (client._backend._client and friends). None if not found."""
        backend = getattr(client, "_backend", None)
        for attr in ("_client", "client", "api", "_api_client"):
            if backend is not None and getattr(backend, attr, None) is not None:
                return getattr(backend, attr)
        return None

    async def _heartbeat(self) -> None:
        """Hold the BLE link inside the firmware's ~36s idle-drop window.

        Sends a cheap 0x2B read only when no real op has run for
        KEEPALIVE_INTERVAL and we look connected — so during normal polling it
        never fires and adds no proxy load; across idle gaps it holds the link
        so we stop paying a full reconnect (and the proxy churn) every cycle."""
        try:
            while True:
                await asyncio.sleep(KEEPALIVE_INTERVAL)
                if self._client is None or not self._client.is_connected:
                    continue
                if (monotonic() - self._last_op) < KEEPALIVE_INTERVAL:
                    continue
                try:
                    await self._request(frame_unit_prime())
                    _LOGGER.debug("keepalive ping ok for %s", self.address)
                except Exception as exc:  # noqa: BLE001
                    _LOGGER.debug(
                        "keepalive ping failed for %s: %s", self.address, exc
                    )
        except asyncio.CancelledError:
            pass

    async def _clear_cache_via_client(self, client: BleakClient) -> None:
        """Clear the bond cache + unpair on the proxy currently servicing this
        client. We reach the underlying aioesphomeapi APIClient through the
        bleak-esphome backend."""
        addr_int = int(self.address.replace(":", ""), 16)
        api = self._proxy_api_client(client)
        if api is None:
            _LOGGER.warning("could not reach proxy APIClient")
            return
        _LOGGER.warning("reached proxy APIClient (%s)", type(api).__name__)
        for op_name, op_call in (
            ("unpair",      lambda: api.bluetooth_device_unpair(addr_int)),
            ("clear_cache", lambda: api.bluetooth_device_clear_cache(addr_int)),
        ):
            try:
                await asyncio.wait_for(op_call(), timeout=8)
                _LOGGER.warning("proxy %s OK for %s", op_name, self.address)
            except Exception as exc:  # noqa: BLE001
                _LOGGER.warning("proxy %s raised: %s: %s", op_name, type(exc).__name__, exc)

    def _all_proxy_api_clients(self) -> list[tuple[str, Any]]:
        """Every ESPHome *bluetooth-proxy* APIClient HA currently knows about.

        Proxies don't share bonds: a bond made via proxy A is invisible to
        proxy B, so a connection routed through B fails with auth errors that
        clearing only the *connected* proxy can't fix.

        We reach each esphome config entry's runtime data defensively (its
        location has moved across HA versions) and keep ONLY entries whose
        device advertises the bluetooth-proxy feature — every esphome APIClient
        exposes ``bluetooth_device_unpair``, but calling it on a non-proxy node
        just blocks until timeout, so the feature flag is the real filter."""
        clients: list[tuple[str, Any]] = []
        for entry in self.hass.config_entries.async_entries("esphome"):
            rd = getattr(entry, "runtime_data", None)
            if rd is None:
                rd = self.hass.data.get("esphome", {}).get(entry.entry_id)
            if rd is None:
                continue
            api = getattr(rd, "client", None)
            if api is None or not hasattr(api, "bluetooth_device_unpair"):
                continue
            di = getattr(rd, "device_info", None)
            flags = 0
            if di is not None:
                flags = getattr(di, "bluetooth_proxy_feature_flags", 0) or getattr(
                    di, "bluetooth_proxy_feature_flags_compat", 0
                )
            if flags:
                clients.append((entry.title or entry.entry_id, api))
        return clients

    async def _clear_bonds_all_proxies(self) -> None:
        """Unpair + clear this device's bond on EVERY proxy, not just the one
        we happened to connect through. Best-effort and concurrent: a proxy that
        never bonded the device just errors harmlessly, and the whole sweep is
        bounded to one short timeout regardless of how many proxies exist."""
        addr_int = int(self.address.replace(":", ""), 16)
        proxies = self._all_proxy_api_clients()
        if not proxies:
            _LOGGER.debug("no esphome BT proxies found for bond clear")
            return
        _LOGGER.warning(
            "clearing %s bonds across %d proxies", self.address, len(proxies)
        )

        async def _clear_one(title: str, api: Any) -> None:
            for op_name, op_call in (
                ("unpair",      lambda: api.bluetooth_device_unpair(addr_int)),
                ("clear_cache", lambda: api.bluetooth_device_clear_cache(addr_int)),
            ):
                try:
                    await asyncio.wait_for(op_call(), timeout=5)
                    _LOGGER.debug("proxy %s %s OK for %s", title, op_name, self.address)
                except Exception as exc:  # noqa: BLE001
                    _LOGGER.debug("proxy %s %s raised: %s", title, op_name, exc)

        await asyncio.gather(
            *(_clear_one(title, api) for title, api in proxies),
            return_exceptions=True,
        )

    def _note_failure(self) -> None:
        """Grow the poll interval on consecutive failures (capped)."""
        self._fail_count += 1
        secs = min(
            POLL_INTERVAL.total_seconds() * (2 ** min(self._fail_count, 4)),
            BACKOFF_MAX.total_seconds(),
        )
        self.update_interval = timedelta(seconds=secs)
        if self._fail_count == 1 or self._fail_count % 5 == 0:
            _LOGGER.warning(
                "poll failing (x%d) — backing off to %ds", self._fail_count, int(secs)
            )

    def _note_success(self) -> None:
        """Reset backoff after a good poll."""
        if self._fail_count:
            _LOGGER.info("poll recovered after %d failure(s)", self._fail_count)
        self._fail_count = 0
        if self.update_interval != POLL_INTERVAL:
            self.update_interval = POLL_INTERVAL

    def _on_disconnected(self, client: BleakClient) -> None:
        _LOGGER.debug("BLE disconnect from %s", self.address)
        self._client = None
        self._state["available"] = False

    async def _disconnect(self) -> None:
        if self._client is not None:
            try:
                await self._client.disconnect()
            except Exception as exc:  # noqa: BLE001
                _LOGGER.debug("disconnect raised: %s", exc)
            self._client = None

    def _on_notify(self, _char, data: bytearray) -> None:
        try:
            frame = self._assembler.feed(bytes(data))
        except IncompleteError:
            return
        except InvalidFrameError as e:
            _LOGGER.warning("invalid frame from %s: %s", self.address, e)
            self._assembler.reset()
            return
        self._last_frame = frame
        self._response_event.set()

    # ---- Op primitives ------------------------------------------------------

    async def _request(self, frame: bytes, *, wait_response: bool = True) -> Any:
        """Send a frame; optionally await one response. Serialized via _lock.

        ``wait_response=True`` (the poll path) blocks up to ``OP_TIMEOUT`` for
        the device's reply notification and returns the parsed frame.

        ``wait_response=False`` (the user-command path) is fire-and-return: it
        writes the ATT Write Command and releases immediately. The water reacts
        on the write itself — the reply notification is only an app-level "got
        it" ack — so making a user command wait up to 10s for that ack (and hold
        the lock the whole time) is the bulk of the "shower takes a minute to
        turn on" lag. The sibling ``mira_mode`` integration fires-and-returns
        and is instant; this matches it. State catches up on the next poll.
        """
        async with self._lock:
            client = await self._ensure_connected()
            self._assembler.reset()
            self._response_event.clear()
            self._last_frame = None
            _LOGGER.debug("→ %s", frame.hex())
            # The official app uses ATT Write Command (response=False) — no
            # ATT-layer ACK round-trip; the device's notification on 267f0003
            # is the application-level "I got it" signal.
            await client.write_gatt_char(
                WRITE_CHAR_UUID, frame, response=False
            )
            # Link held — record so the keepalive heartbeat need not ping.
            self._last_op = monotonic()
            if not wait_response:
                return None
            try:
                await asyncio.wait_for(
                    self._response_event.wait(), timeout=OP_TIMEOUT
                )
            except asyncio.TimeoutError as e:
                raise UpdateFailed(
                    f"timeout waiting for response to {frame.hex()}"
                ) from e
            return self._last_frame

    # ---- Coordinator update loop -------------------------------------------

    async def _async_update_data(self) -> dict[str, Any]:
        """Poll the device (one 0x2B Unit Prime read per cycle)."""
        if not async_address_present(self.hass, self.address, connectable=True):
            self._state["available"] = False
            return self._state
        try:
            frame = await self._request(frame_unit_prime())
        except UpdateFailed:
            self._note_failure()
            raise
        except Exception as e:  # noqa: BLE001
            self._note_failure()
            raise UpdateFailed(f"poll failed: {e}") from e
        self._note_success()
        # Parse the 0x2B response per AB_2B_DECODE.md §2.
        if frame is not None:
            payload_hex = frame.payload.hex()
            parsed = parse_unit_prime(frame.payload)
            if parsed:
                self._state.update(parsed)
                # available: prefer parsed session_ready (bit 6 of byte 0);
                # fall back to "we got a valid response at all".
                self._state["available"] = True
                _LOGGER.debug(
                    "0x2B ← %s : target=%.1f°C flow=%dLPM outlet=0x%02x "
                    "running=%s paused=%s error=%s session_ready=%s "
                    "iot=0x%02x measured=%.1f",
                    payload_hex,
                    parsed["target_temp"],
                    parsed["flow_lpm"],
                    parsed["outlet_state"],
                    parsed["running"],
                    parsed["paused"],
                    parsed["error"],
                    parsed["session_ready"],
                    parsed["iot_status"],
                    parsed["measured_temp"],
                )
            else:
                _LOGGER.warning(
                    "0x2B payload too short to parse: %s", payload_hex
                )
                self._state["available"] = True
        else:
            self._state["available"] = False
        return self._state

    # ---- Public API used by entities ---------------------------------------

    async def async_set_outlet1(self, on: bool) -> None:
        """Toggle outlet B (bit 1 / 0x02). Verified rain head."""
        self._state["outlet1_on"] = on
        await self._send_temperature_frame()

    async def async_set_outlet0(self, on: bool) -> None:
        """Toggle outlet A (bit 0 / 0x01). Inferred handheld."""
        self._state["outlet0_on"] = on
        await self._send_temperature_frame()

    async def async_set_flow_rate(self, flow_raw: int) -> None:
        """Set flow rate. `flow_raw` is the wire byte (LPM × 4). Cap 64."""
        self._state["flow_raw"] = max(0, min(int(flow_raw), 64))
        await self._send_temperature_frame()

    async def _run_brute_force_probe(self) -> None:
        """Try a series of candidate frames and log every response.

        Goal: find the opcode that actually starts water flowing on the
        Mira Activate. Each candidate frame is sent, then we wait up to
        2s for a response, log it, and move on. After the sequence, the
        regular poll resumes — if any candidate flipped an outlet bit
        in the device's response payload, we have our answer.
        """
        from datetime import datetime
        ts = datetime.now().strftime("%y%m%d%H%M%S")  # 12 chars
        # Frame builder helpers (raw — bypass the typed builders).
        def _f(opcode: int, payload: bytes) -> bytes:
            frame = bytes([0xAA, 0x55, 0x00, opcode, len(payload)]) + payload
            return frame + bytes([((~sum(frame) + 1) & 0xFF)])
        candidates = [
            # Most likely to flip iot status: 0xF8 Write Commissioning State.
            # Try each value 0..3; if writing 0x02 makes iot in the next poll
            # decode to 2, we've found the unblock.
            ("F8_state0",  _f(0xF8, bytes([0x00]))),
            ("F8_state2",  _f(0xF8, bytes([0x02]))),
            ("F8_state3",  _f(0xF8, bytes([0x03]))),
            ("F8_state1",  _f(0xF8, bytes([0x01]))),
            # 0xC0 reads bathroom name (per APK f2$c.a) — also serves as a
            # session-establishment ping; harmless to re-send.
            ("C0_v9000",  _f(0xC0, ("9000" + ts).encode("ascii").ljust(18, b"\x00"))),
            # 0xAB outlet write (what we've been doing).
            ("AB_o1_on",  _f(0xAB, bytes([0x01, 0x7C, 0x54, 0x04]))),
            # 0xC2 sub-commands — Write SSid / Tenant id / etc., possible iot
            # auth side door.
            ("C2_sub00",  _f(0xC2, bytes([0x00]))),
            ("C2_sub01",  _f(0xC2, bytes([0x01]))),
            # 0xDD / 0x9B — last-ditch GCS commands.
            ("DD_empty",  _f(0xDD, b"")),
            ("9B_zeros",  _f(0x9B, bytes(16))),
            # Final AB write to see if outlet flips after all the state changes.
            ("AB_o1_on_post", _f(0xAB, bytes([0x01, 0x7C, 0x54, 0x04]))),
        ]
        # Re-entry guard: if a probe is already running, ignore subsequent toggles.
        if getattr(self, "_probe_running", False):
            _LOGGER.warning("PROBE: already running — ignoring re-toggle")
            return
        self._probe_running = True
        _LOGGER.warning("PROBE: starting brute-force candidate sweep, %d frames, ts=%s", len(candidates), ts)
        for name, frame in candidates:
            try:
                async with self._lock:
                    client = await self._ensure_connected()
                    self._assembler.reset()
                    self._response_event.clear()
                    self._last_frame = None
                    _LOGGER.warning("PROBE → %s : %s", name, frame.hex())
                    try:
                        await client.write_gatt_char(WRITE_CHAR_UUID, frame, response=True)
                    except Exception as e:  # noqa: BLE001
                        _LOGGER.warning("PROBE × %s write failed: %s", name, e)
                        await asyncio.sleep(0.5)
                        continue
                    try:
                        await asyncio.wait_for(self._response_event.wait(), timeout=2.5)
                        f = self._last_frame
                        if f is not None:
                            _LOGGER.warning(
                                "PROBE ← %s : opcode=0x%02X payload=%s",
                                name, f.opcode, f.payload.hex(),
                            )
                        else:
                            _LOGGER.warning("PROBE ← %s : (no frame parsed)", name)
                    except asyncio.TimeoutError:
                        _LOGGER.warning("PROBE × %s : no response in 2.5s", name)
                await asyncio.sleep(0.7)
            except Exception as e:  # noqa: BLE001
                _LOGGER.warning("PROBE × %s raised: %s: %s", name, type(e).__name__, e)
                await asyncio.sleep(0.7)
        _LOGGER.warning("PROBE: sweep complete")
        self._probe_running = False

    async def async_set_temperature(self, temp_c: float) -> None:
        """Set target temperature (°C)."""
        self._state["target_temp"] = temp_c
        await self._send_temperature_frame()

    async def async_turn_off_all(self) -> None:
        """Emergency "turn off all outlets" — mirrors the app's
        turnOffAllOutlets path: flags=1, temp=0, flow=0, outlet_state=0."""
        self._state["outlet0_on"] = False
        self._state["outlet1_on"] = False
        self._state["outlet2_on"] = False
        frame = frame_set_temperature(
            flags=1, temp_x10=0, flow_x4=0, outlet_state=0
        )
        try:
            await self._request(frame, wait_response=False)
        except UpdateFailed as e:
            _LOGGER.error("turn-off-all failed: %s", e)
            raise
        self.hass.async_create_task(self.async_request_refresh())

    async def _send_temperature_frame(self) -> None:
        """Build and send a 0xAB frame from the cached desired state.

        Encoding corrected from live HCI snoop 2026-05-30:
          flags           = 0 (the app's `flags` is also always 0 for normal ops)
          temp_x10        = target_temp * 10 (split between byte 5 bit 0 & byte 6)
          byte 7 (flow)   = the device's reported flow_raw (mirror what we got
                            from the last poll — the app does the same)
          byte 8 (outlet) = bit 0=outlet A, bit 1=outlet B, 0x40=pause
        """
        temp_x10 = int(round(self._state["target_temp"] * 10))
        # Echo the last-observed flow_raw back. App defaults to 64 if unknown.
        flow_x4 = int(self._state.get("flow_raw") or 64)
        outlet_state = 0
        if self._state.get("outlet0_on"):
            outlet_state |= OUTLET_BIT_0  # 0x01
        if self._state.get("outlet1_on"):
            outlet_state |= OUTLET_BIT_1  # 0x02
        # outlet2 bit (0x04) is unused on the live device — skip it entirely
        # rather than send an invalid bit the firmware ignores.
        if self._state.get("paused"):
            outlet_state |= OUTLET_PAUSE  # 0x40
        frame = frame_set_temperature(
            flags=0,
            temp_x10=temp_x10,
            flow_x4=flow_x4,
            outlet_state=outlet_state,
        )
        _LOGGER.debug(
            "0xAB → flags=0 temp_x10=%d flow_x4=%d outlet_state=0x%02x "
            "frame=%s",
            temp_x10,
            flow_x4,
            outlet_state,
            frame.hex(),
        )
        try:
            # Fire-and-return so the command lands fast (no 10s ack wait).
            await self._request(frame, wait_response=False)
        except UpdateFailed as e:
            _LOGGER.error("set-temperature failed: %s", e)
            raise
        # Pull fresh state in the background so HA reflects the change without
        # making the user wait on it.
        self.hass.async_create_task(self.async_request_refresh())
